version: 2
jobs:
  build_pytest:
    machine:
      image: circleci/classic:201808-01
    working_directory: /tmp/src/nitransforms
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      FS_LICENSE: "/tmp/fslicense/license.txt"

    steps:
      - restore_cache:
          keys:
            - build-v1-{{ .Branch }}-{{ epoch }}
            - build-v1-{{ .Branch }}-
            - build-v1-master-
            - build-v1-
          paths:
            - /tmp/docker
      - run:
          name: Set-up a Docker registry
          command: |
              docker run -d -p 5000:5000 --restart=always --name=registry \
                  -v /tmp/docker:/var/lib/registry registry:2
      - run:
          name: Pull existing images
          command: |
              set +e
              docker pull localhost:5000/ubuntu
              success=$?
              set -e
              if [[ "$success" = "0" ]]; then
                  echo "Pulling from local registry"
                  docker tag localhost:5000/ubuntu ubuntu:xenial-20200114
                  docker pull localhost:5000/nitransforms
                  docker tag localhost:5000/nitransforms nitransforms:latest
              else
                  echo "Pulling from Docker Hub"
                  docker pull ubuntu:xenial-20200114
                  docker tag ubuntu:xenial-20200114 localhost:5000/ubuntu
                  docker push localhost:5000/ubuntu
              fi
      - checkout
      - run:
          name: Build Docker image & push to registry
          no_output_timeout: 60m
          command: |
              e=1 && for i in {1..5}; do
                  docker build --rm --cache-from=nitransforms:latest \
                  -t nitransforms:latest \
                  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                  --build-arg VCS_REF=`git rev-parse --short HEAD` . \
                  && e=0 && break || sleep 15
              done && [ "$e" -eq "0" ]
              docker tag nitransforms:latest localhost:5000/nitransforms
              docker push localhost:5000/nitransforms
      - run:
          name: Docker registry garbage collection
          command: |
              docker exec -it registry /bin/registry garbage-collect --delete-untagged \
                  /etc/docker/registry/config.yml
      - save_cache:
          key: build-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/docker
      - run:
          name: Check version packaged in Docker image
          command: |
              pyenv local 3.7.0
              python3 -m pip install "setuptools ~= 42.0" "setuptools_scm[toml] >= 3.4" "pip>=10.0.1"
              THISVERSION=${CIRCLE_TAG:-$(python3 setup.py --version)}
              INSTALLED_VERSION=$(\
                docker run -it --rm --entrypoint=python nitransforms \
                    -c 'import nitransforms as nit; print(nit.__version__, end="")' )
              echo "VERSION: \"${THISVERSION}\""
              echo "INSTALLED: \"${INSTALLED_VERSION}\""
              # test "${INSTALLED_VERSION}" = "${THISVERSION}"
      - run:
          name: Store FreeSurfer license file
          command: |
              mkdir -p /tmp/fslicense
              cd /tmp/fslicense
              echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IGxpY2Vuc2UudHh0Cg==" | base64 -d | sh

      - restore_cache:
          keys:
            - data-v1-{{ .Branch }}-{{ epoch }}
            - data-v1-{{ .Branch }}-
            - data-v1-master-
            - data-v1-
          paths:
            - /tmp/data
      - run:
          name: Download data
          command: |
              if [[ ! -d /tmp/data ]]; then
                wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                  -O data.zip "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/5e7d5b65c3f8d300bafa05e0/?zip="
                unzip -d /tmp/data data.zip
              else
                echo "Dataset was cached"
              fi
      - save_cache:
          key: data-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/data
      - run:
          name: Get codecov
          command: python -m pip install codecov
      - run:
          name: Run unit tests
          no_output_timeout: 2h
          command: |
            mkdir -p $PWD/{artifacts,summaries}
            docker run -u $( id -u ) -it --rm -w /src/nitransforms \
              -v /tmp/data:/data -e TEST_DATA_HOME=/data \
              -e COVERAGE_FILE=/tmp/summaries/.pytest.coverage \
              -v /tmp/fslicense/license.txt:/opt/freesurfer/license.txt:ro \
              -v ${PWD}:/tmp nitransforms:latest \
              pytest --junit-xml=/tmp/summaries/pytest.xml \
                     --cov nitransforms --cov-report xml:/tmp/summaries/unittests.xml \
                     nitransforms/
      - run:
          name: Submit unit test coverage
          command: |
            cd /tmp/src/nitransforms
            python -m codecov --file /tmp/tests/summaries/unittests.xml \
                --flags unittests -e CIRCLE_JOB
      - run:
          name: Clean up tests directory
          when: on_success
          command: |
            rm -rf /tmp/tests/pytest-of-root
      - store_artifacts:
          path: /tmp/tests/artifacts

      - store_test_results:
          path: /tmp/tests/summaries/

  test_package:
    docker:
      - image: circleci/python:3.7.4
    working_directory: /tmp/src/nitransforms
    steps:
      - checkout
      - run:
          name: Prepare environment & build
          command: |
            python3 -m venv /tmp/buildenv
            source /tmp/buildenv/bin/activate
            python3 -m pip install "setuptools ~= 42.0" wheel "setuptools_scm[toml] >= 3.4" \
                "pip>=10.0.1" twine docutils
            python setup.py sdist bdist_wheel
            twine check dist/nitransforms*
      - store_artifacts:
          path: /tmp/src/nitransforms/dist
      - persist_to_workspace:
          root: /tmp/src/nitransforms
          paths: dist
      - run:
          name: Install on separate environment and check version [sdist]
          command: |
            python3 -m venv /tmp/install_sdist
            source /tmp/install_sdist/bin/activate
            python3 -m pip install "setuptools ~= 42.0" "pip>=10.0.1"

            THISVERSION=$( python3 setup.py --version )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python3 -m pip install dist/nitransforms*.tar.gz
            INSTALLED_VERSION=$(python3 -c 'import nitransforms as nit; print(nit.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"
      - run:
          name: Install on separate environment and check version [wheel]
          command: |
            python3 -m venv /tmp/install_wheel
            source /tmp/install_wheel/bin/activate
            python3 -m pip install "setuptools ~= 42.0" "pip>=10.0.1"

            THISVERSION=$( python3 setup.py --version )
            THISVERSION=${CIRCLE_TAG:-$THISVERSION}
            python3 -m pip install dist/nitransforms*.whl
            INSTALLED_VERSION=$(python3 -c 'import nitransforms as nit; print(nit.__version__, end="")')
            echo "VERSION: \"${THISVERSION}\""
            echo "INSTALLED: \"${INSTALLED_VERSION}\""
            test "${INSTALLED_VERSION}" = "${THISVERSION}"

  deploy_pypi:
    docker:
      - image: circleci/python:3.7.4
    working_directory: /tmp/src/nitransforms
    steps:
      - attach_workspace:
          at: /tmp/src/nitransforms
      - run:
          name: Upload to Pypi
          command: |
            python3 -m venv /tmp/upload
            source /tmp/upload/bin/activate
            python3 -m pip install twine
            python3 -m twine check dist/*
            python3 -m twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_pytest:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      - test_package:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      - deploy_pypi:
          requires:
            - build_pytest
            - test_package
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
